-- Add multi-modal block types and focus gap xAPI verb
-- ALTER TYPE ADD VALUE must run outside a transaction; IF NOT EXISTS guards idempotency.

ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'SIMULATION';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'VIDEO';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'TEXT_DEEP';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'REAL_WORLD_APP';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'CORRECTIVE_OVERLAY';
ALTER TYPE "BlockType" ADD VALUE IF NOT EXISTS 'CONCEPT_MAP';

ALTER TYPE "XAPIVerb" ADD VALUE IF NOT EXISTS 'focus_gap_detected';
