"""Instructional contracts, not a required menu of lesson components.

Each contract defines the move, its diagnostic trigger, required construction,
evidence of benefit, and when to stop. The planner sees the whole toolbox; the
maker receives only the selected contract.
"""

RESOURCE_TOOLBOX = {
    "mini_lesson": {
        "definition": "Brief explicit teaching of one idea needed for the current activity.",
        "use_when": "A new concept or observed concept gap blocks the saved objective.",
        "avoid_when": "The learner already explains the idea or only needs an unfamiliar word clarified.",
        "must_include": ["One clear explanation", "One concrete worked example", "One contrasting example or misconception", "One fresh check requiring explanation"],
        "success": "Learner explains/applies the idea to the fresh case, rather than repeating the example.",
        "exit": "Return to the investigation after the check; if unsuccessful, locate the specific obstacle before adding instruction.",
        "max_minutes": 8,
    },
    "guided_practice": {
        "definition": "Practice of one exact skill with support that fades as the learner succeeds.",
        "use_when": "Learner can follow an explanation but cannot yet perform the procedure independently; identify the failing step.",
        "avoid_when": "The underlying concept is unknown, or the learner already performs the skill independently.",
        "must_include": ["Name the exact skill", "Model one representative task with reasoning", "Provide one partially supported task", "Provide one new independent task", "Feedback must respond to the actual error"],
        "success": "A fresh independent attempt succeeds with reasoning and without copied answers/hints.",
        "exit": "Remove support after success; if the same error persists, diagnose the prerequisite or misconception rather than issuing more repetitions.",
        "max_minutes": 15,
    },
    "vocabulary_support": {
        "definition": "Clarify a specific term that obstructs access to an otherwise accessible concept.",
        "use_when": "Learner asks what a term means, repeatedly misuses it in a way that blocks reasoning, or can explain the idea in ordinary language but cannot interpret its technical label.",
        "avoid_when": "A word merely appears in the lesson, the learner reads slowly, or a concept gap is being mistaken for a word gap. Ask a diagnostic question if uncertain.",
        "must_include": ["Identify the exact obstructing term", "Plain-language meaning in this lesson's context", "Concrete example and non-example", "Connect the term to something already understood", "One interpretation/use check in a fresh context"],
        "success": "Learner interprets or uses the term accurately to reason about the current evidence; memorized definitions alone are insufficient.",
        "exit": "Return to the activity immediately when the barrier clears. If understanding still fails after clarification, teach the concept instead.",
        "max_minutes": 3,
    },
    "worked_examples": {
        "definition": "A small sequence showing how and why a solution is constructed.",
        "use_when": "Learner needs to see a strategy or representative variations before attempting it.",
        "avoid_when": "Learner is ready for independent practice; do not supply the answer to the current evidence task.",
        "must_include": ["Reasoning at each important step", "Two cases differing in a meaningful feature", "One analogous unsolved task"],
        "success": "Learner selects and explains the strategy on the unsolved task.",
        "exit": "Move to an independent attempt rather than another demonstration.",
        "max_minutes": 10,
    },
    "comparison": {
        "definition": "Contrast cases that reveal an important distinction.",
        "use_when": "Learner confuses categories, such as observation/inference or correlation/causation.",
        "avoid_when": "Learner cannot yet describe either concept; teach the missing idea first.",
        "must_include": ["Two to four contrasting cases", "A discriminating feature", "A fresh classification requiring justification"],
        "success": "Learner classifies a new case and justifies the boundary.",
        "exit": "Resume the canonical evidence task after the distinction is demonstrated.",
        "max_minutes": 8,
    },
    "visual_model": {
        "definition": "An explicit representation of relationships or a mechanism, described in text or constructed by the learner.",
        "use_when": "Learner knows individual facts but cannot relate parts, steps, causes or quantities.",
        "avoid_when": "Decoration would add no explanatory value; this text maker cannot claim it displayed a generated image.",
        "must_include": ["Define each represented element", "Show the relationships", "State a limitation of the model", "Ask the learner to predict or explain with the model"],
        "success": "Learner uses the representation to make and justify a prediction.",
        "exit": "Return to the actual phenomenon; do not mistake the model for evidence.",
        "max_minutes": 10,
    },
    "retrieval": {
        "definition": "Recall previously taught knowledge from memory with corrective feedback.",
        "use_when": "A taught skill is due for recall or available evidence suggests forgetting.",
        "avoid_when": "The concept has never been taught or time pressure would confound understanding.",
        "must_include": ["Three to five brief prompts", "Recall before looking at explanations", "Check errors with Adeline", "One meaningful application"],
        "success": "Learner retrieves and applies the idea without cues; speed is not the criterion.",
        "exit": "Stop after adequate evidence; repair particular errors instead of extending the quiz.",
        "max_minutes": 8,
    },
    "investigation": {
        "definition": "Observe or test a question with a method that can distinguish explanations.",
        "use_when": "Direct evidence or a safe experiment will resolve the current question.",
        "avoid_when": "A demonstration cannot test the proposed claim, materials are unavailable, or the procedure is unsafe.",
        "must_include": ["Testable question", "Materials and availability check", "Safe method with controls/variables where applicable", "What data to collect", "Interpretation and limits"],
        "success": "Learner connects observations to the claim while acknowledging what remains untested.",
        "exit": "Return with evidence; inconclusive findings are acceptable and never fabricated.",
        "max_minutes": 20,
    },
    "evidence_set": {
        "definition": "A bounded set of supplied sources or clearly simulated records for comparing claims.",
        "use_when": "Learner needs to corroborate, evaluate competing explanations, or distinguish evidence from assertion.",
        "avoid_when": "Actual source content is unavailable; catalog descriptions are not quotations or full records.",
        "must_include": ["Identify source or simulated status", "Observation/inference distinction", "Competing explanations", "Question about corroboration or missing evidence"],
        "success": "Learner supports a proportionate conclusion and names its uncertainty.",
        "exit": "Apply the reasoning to the canonical claim rather than creating an endless case file.",
        "max_minutes": 15,
    },
    "transfer_task": {
        "definition": "Apply a demonstrated idea to a meaningfully new situation.",
        "use_when": "Current evidence supports readiness to use the concept beyond the worked example.",
        "avoid_when": "Essential prerequisites are missing; an invented recipient is not real service.",
        "must_include": ["A new situation and concrete task", "Relevant constraints", "A deliverable", "Evidence showing why the solution works"],
        "success": "Learner adapts the idea and defends the adaptation.",
        "exit": "Record the evidence through the existing review path; do not auto-award mastery.",
        "max_minutes": 20,
    },
    "stations": {
        "definition": "Several coordinated family tasks serving the same investigation.",
        "use_when": "Parallel work genuinely improves observation or lets siblings contribute at different depths.",
        "avoid_when": "Rotation adds logistics without learning value, or required materials/participants are unknown.",
        "must_include": ["Two or three purposeful tasks", "Different learner roles", "Shared facts", "A synthesis of findings"],
        "success": "Each learner supplies their own reasoning and the family connects the findings.",
        "exit": "Rejoin the shared investigation; another sibling's performance is not individual mastery.",
        "max_minutes": 20,
    },
    "reading_support": {
        "definition": "Reduce an access barrier while preserving the disciplinary idea.",
        "use_when": "Evidence shows decoding, dense syntax or text organization obstructs subject understanding.",
        "avoid_when": "Grade alone is the diagnosis, or simplifying would remove the concept being learned.",
        "must_include": ["Preserve the concept and important technical terms", "Chunk/rephrase the supplied explanation", "Explain context", "Check conceptual understanding separately from decoding"],
        "success": "Learner reasons about the concept once the text barrier is reduced.",
        "exit": "Return to the main task; do not label a reading difficulty as a science misconception.",
        "max_minutes": 10,
    },
    "extension": {
        "definition": "Increase intellectual complexity after understanding is demonstrated.",
        "use_when": "Learner has shown the current understanding and is ready for limits, alternative explanations or quantitative depth.",
        "avoid_when": "Fast completion, age, or confidence is the only evidence of readiness; more of the same is not an extension.",
        "must_include": ["Connect to the same canonical idea", "One genuinely deeper constraint/question", "Reasoned evidence requirement"],
        "success": "Learner handles the added complexity and explains the limits.",
        "exit": "Return to the shared scene; do not generate an independent curriculum.",
        "max_minutes": 15,
    },
    "performance_task": {
        "definition": "Elicit reviewable evidence of one specified objective with minimal prompting.",
        "use_when": "Understanding is uncertain or a fresh demonstration is needed.",
        "avoid_when": "The requested demonstration already exists, or supports reveal the answer being assessed.",
        "must_include": ["Exact task and observable criterion", "A fresh situation", "Reasoning or product to review", "Allow oral/written/constructed evidence where appropriate"],
        "success": "Evidence demonstrates the objective without answer-carrying help.",
        "exit": "Send the demonstration to the existing evaluator; a task completion is not mastery.",
        "max_minutes": 15,
    },
}
