export const INTERESTS_OPTIONS = [
  'Coding',
  'Gardening',
  'Science',
  'Reading',
  'Art',
  'Animals',
  'History',
  'Sports',
  'Music',
  'Building',
  'Nature',
  'Stories',
  'Math',
  'Cooking',
  'Technology',
  'Writing',
];

export const LEARNING_STYLES = [
  {
    value: 'EXPEDITION',
    label: 'Expedition Mode',
    description:
      'Cross-curricular journey — explore topics by connecting science, history, art, and more. Perfect for curious learners who love making connections.',
  },
  {
    value: 'CLASSIC',
    label: 'Classic Mode',
    description:
      'Traditional subjects — focus on core academics (math, ELA, science, history) with clear learning objectives. Great for structured learners.',
  },
];

export const US_STATES = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];
